name: poppy
version: 0.1.8
authors:
- Ahmet A. Akın <ahmetaa@gmail.com>
- Mehmet D. Akın <mdakin@gmail.com>
description: Some algorithms for Dart. Such as Trie, MPHF and Bloom Filter.
homepage: https://github.com/ahmetaa/poppy
dependencies:
  unittest: '>=0.4.0'
